name: Act tests CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "tests/**"
      - ".github/workflows/pr-checks-test-ci.yml"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
    paths:
      - "tests/**"
      - ".github/workflows/pr-checks-test-ci.yml"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACT_VERSION: v0.2.82
  GOLANGCI_LINT_VERSION: "2.7.2"

permissions:
  contents: read

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-arm64-small
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: tests/act/go.mod
          cache-dependency-path: tests/act/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: tests/act

  act-tests:
    name: Act tests
    runs-on: ubuntu-x64-xlarge-io
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0
          lfs: true

      # This is needed otherwise actions/checkout puts the repo in detached head
      # and act complains it cannot determine to which branch the current commit belongs to.
      - name: Checkout branch
        run: |
          git checkout "${REF}"
        env:
          REF: ${{ github.event.pull_request.head.ref || github.ref }}
        shell: bash

      - name: Install act
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b /usr/bin "${ACT_VERSION}"
        env:
          ACT_VERSION: ${{ env.ACT_VERSION }}
          GH_TOKEN: ${{ github.token }}
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: tests/act/go.mod
          cache-dependency-path: tests/act/go.sum

      # TODO: introduce some caching for act tool cache docker volume and nektos/act docker image

      - name: Run act tests
        run: |
          go test -v -timeout 1h
        working-directory: tests/act
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
