name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  ACTIONLINT_VERSION: "1.7.10"
  GOLANGCI_LINT_VERSION: "2.7.2"

jobs:
  actionlint:
    runs-on: ubuntu-arm64-small
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Enable action lint matcher
        run: echo "::add-matcher::.github/actionlint-matcher.json"
      - name: Download actionlint
        id: get_actionlint
        run: |
          bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTIONLINT_VERSION}/scripts/download-actionlint.bash") "${ACTIONLINT_VERSION}" "/usr/local/bin"
        shell: bash
        env:
          ACTIONLINT_VERSION: ${{ env.ACTIONLINT_VERSION }}
      - name: Check workflow files
        run: |
          actionlint -color
        shell: bash

  lint:
    name: Lint ${{ matrix.directory }}
    runs-on: ubuntu-arm64-small
    strategy:
      fail-fast: false
      matrix:
        directory:
          - tests/act
          - examples/base
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: ${{ matrix.directory }}/go.mod
          cache-dependency-path: ${{ matrix.directory == 'tests/act' && 'tests/act/go.sum' || '' }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.directory }}
