name: Act tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "tests/**"
      - ".github/workflows/test-act.yml"
      - ".github/workflows/ci.yml"

env:
  ACT_VERSION: v0.2.82

permissions:
  contents: read

jobs:
  act-tests:
    name: Act tests
    runs-on: ubuntu-x64-large
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Install act
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b /usr/bin "${ACT_VERSION}"
        #run: |
        #  gh extension install https://github.com/nektos/gh-act --pin "${ACT_VERSION}"
        env:
          ACT_VERSION: ${{ env.ACT_VERSION }}
          GH_TOKEN: ${{ github.token }}
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      
      - name: (Lapo) Prepare for act tests
        run: |
          rm -rf /tmp/plugin-ci-workflows
          cd /tmp
          git clone -b giuseppe/act https://github.com/grafana/plugin-ci-workflows.git
        shell: bash

      - name: Run act tests
        run: |
          go run main.go
        working-directory: /tmp/plugin-ci-workflows/tests/act
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
