name: Smoke test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "tests/**"
      - ".github/workflows/test-ci.yml"
      - ".github/workflows/ci.yml"

permissions: {}

jobs:
  find-tests:
    name: Find tests
    runs-on: ubuntu-arm64-small
    permissions:
      contents: read
    outputs:
      plugin-directories: ${{ steps.set-output.outputs.plugin-directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Find test plugin
        id: set-output
        run: |
          cd tests
          plugins=$(find . -maxdepth 1 -type d ! -name '.' -printf '%f\n' | jq -R . | jq -cs .)
          echo "plugin-directories=$plugins" >> "$GITHUB_OUTPUT"

  simple-ci:
    name: CI
    needs: find-tests
    strategy:
      matrix:
        plugin-directory: ${{ fromJson(needs.find-tests.outputs.plugin-directories) }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ci.yml
    with:
      # Treat as untrusted and disable GCS and Vault access
      # (WIF access is not available from plugin-ci-workflows itself)
      testing: true

      # Build the specific plugin from the matrix
      plugin-directory: tests/${{ matrix.plugin-directory }}

      # Differentiate each plugin's "dist-artifacts" name so they don't clash with each other
      dist-artifacts-prefix: ${{ matrix.plugin-directory }}-

      # Like in the other examples, append the plugin version the PR SHA for PRs and nothing for pushes
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}

      # TODO: enable in a follow-up PR
      run-playwright: false
  
  ci-plugin-validator:
    name: CI plugin-validator
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ci.yml
    with:
      testing: true
      plugin-directory: tests/simple-backend
      dist-artifacts-prefix: custom-inputs
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: false

      run-plugin-validator: true


