name: Act tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "tests/**"
      - ".github/workflows/test-act.yml"
      - ".github/workflows/ci.yml"

env:
  ACT_VERSION: v0.2.82

permissions:
  contents: read

jobs:
  act-tests:
    name: Act tests
    runs-on: ubuntu-x64-large
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0

      # This is needed otherwise actions/checkout puts the repo in detached head
      # and act complains it cannot determine to which branch the current commit belongs to.
      - name: Checkout branch
        run: |
          git checkout "${REF}"
        env:
          REF: ${{ github.event.pull_request.head.ref || github.ref }}
        shell: bash

      - name: Install act
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b /usr/bin "${ACT_VERSION}"
        env:
          ACT_VERSION: ${{ env.ACT_VERSION }}
          GH_TOKEN: ${{ github.token }}
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: tests/act/go.mod
          cache-dependency-path: tests/act/go.sum

      # TODO: introduce some caching for act tool cache docker volume and nektos/act docker image

      - name: Run act tests
        run: |
          go test -v
        working-directory: tests/act
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
